### ISSUE TITLE
Fix Quote unicode encoding

### ISSUE THREAD

**Issue by llimllib** [llimllib/limbo#13]
urllib.quote doesn't handle unicode strings, so all uses of it need to encode the string. See https://github.com/UnILabKAIST/slask/commit/8071510d5ebaa3b73625963c8da9a63cce3d23af for examples.

**Comment by llimllib** [comment]
and test the resulting fixes

**Comment by ff-** [comment]
Maybe using python3 would fix the issue?

**Comment by llimllib** [comment]
It would! But I definitely don't want to throw python2 users under the bus (*cough* me *cough*).

The real solution is probably to define a utils module with a quote function that works the same in python2 and python3.

**Comment by llimllib** [comment]
Fixed half of them in https://github.com/llimllib/limbo/commit/cf460252c7baa7fe9e19a4a9b80ad00aae53cb27, the other half to come shortly

**Comment by llimllib** [comment]
Finally all done! release 3.0.0 should not have any issues with unicode gifs.
