### ISSUE TITLE
"hit me" command to get another GIF from last query

### ISSUE THREAD

**Issue by noise** [llimllib/limbo#25]
requires #18

**Comment by llimllib** [comment]
Actually requires https://github.com/llimllib/slask/issues/26

**Comment by topher200** [comment]
This was attempted with #30. However, the contributor didn't like the user experience and elected to close the pull request.

Since this was attempted and deemed to be Not Great™️, I'm going to close. If anyone's looking to pick this back up, reopen and check out #30.
