### ISSUE TITLE
figlet plugin

### ISSUE THREAD

**Issue by llimllib** [llimllib/limbo#41]
create a plugin to generate text banners with [pyfiglet](https://pypi.python.org/pypi/pyfiglet/0.7.1). This will be an interesting test because we will have to create an attachment rather than just return the text (right?)

```
In [4]: pyfiglet.print_figlet("bananas")
 _
| |__   __ _ _ __   __ _ _ __   __ _ ___
| '_ \ / _` | '_ \ / _` | '_ \ / _` / __|
| |_) | (_| | | | | (_| | | | | (_| \__ \
|_.__/ \__,_|_| |_|\__,_|_| |_|\__,_|___/



In [5]: pyfiglet.print_figlet("bananas", font="slant")
    __
   / /_  ____ _____  ____ _____  ____ ______
  / __ \/ __ `/ __ \/ __ `/ __ \/ __ `/ ___/
 / /_/ / /_/ / / / / /_/ / / / / /_/ (__  )
/_.___/\__,_/_/ /_/\__,_/_/ /_/\__,_/____/
```

**Comment by noise** [comment]
should be able to just return the text if you can figure how to declare you want it monospaced? and if tha t works we can do a cowsay plugin too!

**Comment by llimllib** [comment]
testing slack rendering bug:

create a plugin to generate text banners with [pyfiglet](https://pypi.python.org/pypi/pyfiglet/0.7.1). This will be an interesting test because we will have to create an attachment rather than just return the text (right?)

```
In [4]: pyfiglet.print_figlet("bananas")
 _
| |__   __ _ _ __   __ _ _ __   __ _ ___
| '_ \ / _` | '_ \ / _` | '_ \ / _` / __|
| |_) | (_| | | | | (_| | | | | (_| \__ \
|_.__/ \__,_|_| |_|\__,_|_| |_|\__,_|___/



In [5]: pyfiglet.print_figlet("bananas", font="slant")
    __
   / /_  ____ _____  ____ _____  ____ ______
  / __ \/ __ `/ __ \/ __ `/ __ \/ __ `/ ___/
 / /_/ / /_/ / / / / /_/ / / / / /_/ (__  )
/_.___/\__,_/_/ /_/\__,_/_/ /_/\__,_/____/
```

**Comment by llimllib** [comment]
Closed in https://github.com/llimllib/limbo/commit/68fb9e85b69313ef928d943dbe2cd0b0e9e386f7
