### ISSUE TITLE
slackrtm vs python-slackclient

### ISSUE THREAD

**Issue by jonathan-s** [llimllib/limbo#64]
Just out of curiousity I was wondering why you forked the python-slackclient and use that rather than the one that is officially maintained. Any particular reason?

**Comment by llimllib** [comment]
Sure, it was an annoying choice to make:

python-slackclient:

* doesn't update frequently
* wasn't responding in reasonable periods of time to bug reports
* it's not very pythonic, it makes some bizarre API choices ([this](https://github.com/slackhq/python-slackclient/blob/master/slackclient/_util.py#L1) is the one that jumps to mind)

**Comment by llimllib** [comment]
Also, it's pretty simple so I forked it; I'd probably like to go in and simplify it even more.

**Comment by jonathan-s** [comment]
Yeah, it is annoying that they aren't very responsive in terms of updating it. There seems to be people willing to put time and effort into making it better, but it seems like there isn't a will to let go of some control to make faster updates.

**Comment by llimllib** [comment]
Oh I also added a few more tests and tox to test against multiple versions, but there's lots that could be done in that dimension.

Anyway, I'm going to close, but I should probably write all this into the slackrtm readme!
