### ISSUE TITLE
command "!search/!google what is something" raise IndexError

### ISSUE THREAD

**Issue by otnt** [llimllib/limbo#66]
Platform: OSX 10.11.3
Python version: Python 2.7.11

Problem:
All the following chats raise IndexError: list index out of range
!search what is apple
!search what is banana
!search what is slack
!google what is apple
!google what is banana
!google what is slack

But not all these pattern chatting raise IndexError. For instance, this is okay:
!search what is abc123
!google what is abc123

**Comment by TetraEtc** [comment]
I'll look into this tonight. Appears to be things that googles smart translation/definition widget. 

if @llimllib agrees though it might be better to use googles API instead of soup?

**Comment by TetraEtc** [comment]
#69 should fix this

**Comment by llimllib** [comment]
I remember there being a reason why google's API was unusable, but I can't remember what it is.

Definitely would be better if possible!

**Comment by TetraEtc** [comment]
I think the fix in #69 should be good enough for now.

Registering for a Google developer API key can be a pain. This method works
well enough.
