### ISSUE TITLE
Avoid slack parsing when getting message

### ISSUE THREAD

**Issue by jonathan-s** [llimllib/limbo#68]
Do you know if it's possible to avoid slack parsing the message when you recieve a message? Ie a message like `honshuu-api-lb1.wdc.sl` will be parsed as `<http://honshuu-api-lb1.wdc.sl|honshuu-api-lb1.wdc.sl>` which isn't desirable.

**Comment by jonathan-s** [comment]
I solved it by doing a search and replace with regex. But if you know anything of turning off parsing it could be useful.

**Comment by llimllib** [comment]
Unfortunately, no, it's a limitation of the Slack RTM API that we receive messages formatted by slack, like the one you showed.
