### ISSUE TITLE
please add a "time" or a  "delayed" indicator to the stock plugin 

### ISSUE THREAD

**Issue by jalsco** [llimllib/limbo#77]
for example when i get a quote for WBC.AX  google returns this: 

Westpac Banking Corp Fully Paid Ord. Shrs
ASX: WBC - 5 Jul., 10:24 am AEST
28.56AUDPrice decrease0.42 (1.47%)

limbo formats it very nicely -  BUT - the actual quote provided by google is 20 minutes lag to current time.  I just want to be reminded that it is a quote from the past -- "DELAYED QUOTE - 20MINS"  or just show the time..   However is easiest to do it -- please. 

Also - Thank you for a great product - am loving limbo ! :)

**Comment by jalsco** [comment]
and also handle the stocks like WBC.AX  <-- this handled in google byt not by limbo stocks plugin

**Comment by llimllib** [comment]
@jalsco I know nothing about stocks, so if you can answer a question for me, that'd help implement the second bit. What are valid stock ticker symbols with periods in them? Are they all of the format xxx.xx?

**Comment by jalsco** [comment]
it is really easy to check ---  basically the foramt that yahoo finance and google use is XXX.AX  --> means it is on the Australian exchange the ASX ..    the stock plugin just gets the quote from google . To see what valid just type it to : https://www.google.com/finance   

so without any extnsion means US stocks -- like NYSE or NASDAQ 
or with an extension is another country  --

**Comment by jalsco** [comment]
i mean jsut send it to google finance -- if nothing comes back -- show "no quote available"  -- is something comes back -- as it will for WBC.AX -- show it ... 

BTW -- I was playing with limbo all afternoon - IT IS SO AWESOME !! -- thank you !!  for some great  work !! . Am already working on plugin ;)

**Comment by jalsco** [comment]
heree's the definitive list : 
http://finance.yahoo.com/exchanges

**Comment by llimllib** [comment]
ah great! that list is super helpful.

**Comment by llimllib** [comment]
Sorry for the world's slowest response time!
