### ISSUE TITLE
Don't swallow message_changed messages

### ISSUE THREAD

**Issue by nedbat** [llimllib/limbo#78]
I'd like to see updates to messages as users edit them, but the core looks specifically for "message_changed" subtypes and ignores them.  Why is this one subtype special enough to hide from me? :(

**Comment by llimllib** [comment]
That is a very good question. Removing.

**Comment by llimllib** [comment]
(I'm sure I had a reason at some point, but it doesn't make any sense to me either)

**Comment by llimllib** [comment]
Updating to version `5.0.0` should give your plugins access to the `on_message_changed` hook. Hope it works for you, let me know if it doesn't, and thanks for the report.
