### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by bsmoo** [llimllib/limbo#87]
Is there anyway we can post pretty hyperlinks like [checkout here for more info](http://example.com)?

I see this was raised in #68, but i was wondering if there was a way to tell the bot to reply via the API rather than as a bot. I can create a simple curl request and get the hyperlinks formatted as the above?

**Comment by llimllib** [comment]
Yup! The plugins receive the server object, which has the slack API avaialble at `server.slack`. The github plugin, for example, [uses the API to post messages](https://github.com/llimllib/limbo/blob/master/limbo/plugins/github.py#L335), though it uses attachments to do so.

A simple way to send a message with a link would be, in your `on_message` function:

```
server.slack.post_message(msg['channel'], 'you can <http://example.com|checkout here for more info>')
```
