### ISSUE TITLE
User entering room

### ISSUE THREAD

**Issue by bsmoo** [llimllib/limbo#88]
Anyway to listen out for users entering the room? I'm like to send them a direct message of the `!help` command

**Comment by llimllib** [comment]
Not currently! There needs to be a `presence_change` handler added to event_handlers for that.

I'm happy to add it, and that's an important use case, but my wife is supposed to give birth this afternoon so it may take a few days :)

**Comment by llimllib** [comment]
OK, I found an hour where I had some nervous energy so I got it done; turns out it was easier than I thought.

After you upgrade to version 5.1.0, here's a change you could make to the help plugin to do what you're asking for. The `on_channel_join` handler is what does the work:

```
diff --git a/limbo/plugins/help.py b/limbo/plugins/help.py
index 1d79f52..6a51f6c 100644
--- a/limbo/plugins/help.py
+++ b/limbo/plugins/help.py
@@ -2,6 +2,10 @@

 import re

+def get_all_help(server):
+    helpdict = server.hooks.get("help", {})
+    return "\n".join(sorted(helpdict[key] for key in helpdict))
+
 def on_message(msg, server):
     text = msg.get("text", "")
     match = re.findall(r"!help( .*)?", text)
@@ -13,6 +17,9 @@ def on_message(msg, server):
         return server.hooks["extendedhelp"].get(helptopic,
                 "No help found for {0}".format(helptopic))
     else:
-        # if no plugin has a docstring, there's no help key
-        helpdict = server.hooks.get("help", {})
-        return "\n".join(sorted(helpdict[key] for key in helpdict))
+        get_all_help(server)
+
+def on_channel_join(msg, server):
+    server.slack.post_message(msg['user'],
+        get_all_help(server),
+        as_user=server.slack.username)
```

**Comment by llimllib** [comment]
btw it was #89 that fixed this, just to link the patch

**Comment by bsmoo** [comment]
Wow! great fast work!

**Comment by bsmoo** [comment]
What do you think the best way of making this only alert particular channels?

**Comment by llimllib** [comment]
just check msg['channel'] and see if it's in a list of channels you want to alert
