### ISSUE TITLE
multi-input

### ISSUE THREAD

**Issue by bsmoo** [llimllib/limbo#90]
Hey,

What's your preferred method of reading multiple inputs? such as the below:

```
!calendar 2016-05-25 busy
```

**Comment by llimllib** [comment]
There are two approaches I use:

1. Break the message into multiple bits by regex, like `re.findall(r'!calendar (\w*) (\w*)')`
2. Use [argparse](https://docs.python.org/dev/library/argparse.html) to parse the command. The [banner plugin](https://docs.python.org/dev/library/argparse.html) uses this approach, for example
