### ISSUE TITLE
Messages capped at 1000 characters

### ISSUE THREAD

**Issue by bsmoo** [llimllib/limbo#91]
Are messages capped? I'm sending a 2500 character message and it's being sent in three messages. This causes issues as I wrap it in triple backticks.

**Comment by llimllib** [comment]
messages sizes are capped by slack, and limbo automatically breaks them and sends as multiple messages as the least bad alternative.

If you want to send a large file, it's probably best to use file.upload: https://api.slack.com/methods/files.upload

Here's an example from a non-public plugin of mine where I do this to upload an image:

```
    r = server.slack.api_call("files.upload",
        post_data={"channels": msg["channel"]},
        files={'file': ('{}.png'.format(chart), img, 'image/png')})
```

And here is the code in limbo that does the message breaking: https://github.com/llimllib/limbo/blob/master/limbo/limbo.py#L179 which has a detailed comment about why it's 1000 characters.
