### ISSUE TITLE
Move from rtm.start -> rtm.connect

### ISSUE THREAD

**Issue by llimllib** [llimllib/limbo#95]
https://api.slack.com/changelog/2017-04-start-using-rtm-connect-and-stop-using-rtm-start

**Comment by topher200** [comment]
Here's all the data that we use from `rtm.start` and whether or not it's going away:

Response data | Present in `rtm.connect`
----------|-------------
`ok`|:white_check_mark:
`url`|:white_check_mark:
`team`.`domain`|:white_check_mark:
`self`.`name`|:white_check_mark:
`self`.`id`|:white_check_mark:
`channels`|:x:
`groups`|:x:
`ims`|:x:
`users`|:x:
`bots`|:x:

**Comment by llimllib** [comment]
@topher200 willing to code review if I update?

**Comment by topher200** [comment]
Sure!
